name: Auto Update Fuel Prices

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch: 

permissions:
  contents: write   # <-- এই লাইনটি বটকে ফাইল সেভ করার পারমিশন দেবে

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4   # <-- ওয়ার্নিং সরাতে v4 করা হলো

      - name: Setup Python
        uses: actions/setup-python@v5   # <-- ওয়ার্নিং সরাতে v5 করা হলো
        with:
          python-version: '3.10'

      - name: Run Scraper Script
        run: python scraper.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "JSR-OS Bot"
          git config --global user.email "bot@jsrdigital.in"
          git add fuel_prices.json
          git commit -m "Auto-update daily fuel prices" || exit 0
          git push
